# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-normal
  namespace: argo
spec:
  template:
    spec: {}
