# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-normal
  namespace: argo
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
spec:
  clusterName: 3f4fa27d-bb41-4174-809b-b4cfa8132369
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-normal
      clusterName: 3f4fa27d-bb41-4174-809b-b4cfa8132369
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-normal
      version: v1.22.3

