# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-taco
  namespace: argo
spec:
  clusterName: 3f4fa27d-bb41-4174-809b-b4cfa8132369
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-taco
      clusterName: 3f4fa27d-bb41-4174-809b-b4cfa8132369
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: 3f4fa27d-bb41-4174-809b-b4cfa8132369-md-taco
      version: v1.22.3
